---
language: python
python: "3.8"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
# env:
#   - ANSIBLE_VERSION=2.10.7
#   - ANSIBLE_LINT_VERSION=5.0.6

branches:
  only:
    - main

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip3 install ansible==3.1.0
  - pip3 install ansible-lint==5.0.6
  - pip3 install yamllint==1.26.0

script:
  # Run the ansible-lint with ansible-role
  - ansible-lint
  - yamllint .
