---
language: python
python: "3.8"

branches:
  only:
    - main

before_install:
  - sudo apt-get update -qq

services:
  - docker

install:
  # Install packages
  - pip3 install -r requirements.txt

script:
  - molecule --version
  - ansible --version
  - molecule -v converge
  - molecule -v verify
