---

- name: Deploy Docker on all VM
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Ensure that iptables is installed
    yum:
      name: iptables.x86_64
      state: installed
    check_mode: true
    register: mypackage_check

  - name: install iptables if necessary
    yum:
      name: iptables.x86_64
      update_cache: yes
    when: mypackage_check.changed

  - name: Deploy Docker on server
    import_role:
      name: "jgeusebroek.docker"
    vars:
      docker_tls_enable: True
      docker_tls_bind: '{{ ansible_default_ipv4.address }}'
      docker_tls_port: 2376
      docker_tls_basepath: '/etc/docker'
      docker_tls_keys:
        ca_cert: "{{ lookup('file', './certificates/ca-cert.pem') }}"
        server_cert: "{{ lookup('file', './certificates/server-cert.pem') }}"
        server_key: "{{ lookup('file', './certificates/server-key.pem') }}"
  
  - name: Resolve IP table problem for docker on CentOS 8
    ansible.builtin.shell: |
      set -o pipefail 
      iptables -I INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
    args:
       executable: /bin/bash
    register: results
    changed_when: 'results.stdout_lines == []'

  - name: Start docker.service, if not started
    ansible.builtin.service:
      name: docker
      state: started

  - name: Make sure the docker.service is running on boot
    ansible.builtin.systemd:
      enabled: yes
      name: docker.service
      
  - name: Make sure the containerd.service is running on boot
    ansible.builtin.systemd:
      enabled: yes
      name: containerd.service