---

- name: Deploy Docker on all VM
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Intall iptables tools
    yum: name=iptables update_cache=yes

  - name: Deploy Docker on server
    import_role:
      name: "geerlingguy.docker"
    ignore_errors: yes
  
  # Issue: docker.service failed because the control process exited with error code
  # It appears sometimes and I didn't understand from what exactly it depends
  # Working solution is from: https://stackoverflow.com/a/66383085

  - name: Resolve IP table problem for docker on CentOS 8
    ansible.builtin.shell: |
      set -o pipefail 
      iptables -I INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
    args:
       executable: /bin/bash
    register: results
    changed_when: 'results.stdout_lines == []'

  - name: Start docker.service, if not started
    ansible.builtin.service:
      name: docker
      state: started

  # following recommendations from https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot
  - name: Make sure the docker.service is running on boot
    ansible.builtin.systemd:
      enabled: yes
      name: docker.service
  - name: Make sure the containerd.service is running on boot
    ansible.builtin.systemd:
      enabled: yes
      name: containerd.service