---
- name: Install LVM2 tools.
  yum:
    name: lvm2
    update_cache: true
  
- name: Creat lvm on empty disk.
  import_role:
    name: ansible-role-disk
  vars:
    parted:
      - device: "{{ alternative_block_device }}"
        number: 1
        label: gpt
        state: present
    lvg:
      - vg: "{{ alternative_vg_name }}"
        pvs: 
        - "{{ alternative_block_device }}1"
    lvol:
      - vg: "{{ alternative_vg_name }}"
        lv: "{{ alternative_lv_name }}"
        linear: yes
        size: 100%VG
    filesystem:
      - fstype: xfs
        dev: "/dev/{{ alternative_vg_name }}/{{ alternative_lv_name }}"
    mount:
      - path: "{{ alternative_docker_dir }}"
        src: "/dev/{{ alternative_vg_name }}/{{ alternative_lv_name }}"
        fstype: xfs
        opts: defaults      
