---
- name: Ensure that iptables is installed
  yum:
    name: iptables.x86_64
    state: installed
  notify: install iptables

- name: Install docker.
  include_role:
    name: geerlingguy.docker
  vars:
    docker_users: docker

- name: Creates directory for user 'docker'.
  file:
    path: /home/docker/.ssh
    state: directory
    owner: docker
    group: docker
    mode: '0755'

- name: Copy and set owner/group/permissions to user 'docker' for ssh connection.
  copy:
    src: "{{ pub_key_path }}/{{ pub_key_name }}"
    dest: /home/docker/.ssh/authorized_keys
    group: docker
    owner: docker
    mode: '0644'

- name: Install docker-python package.
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
    - name: docker

- name: Change DOCKER_ROOT_DIR if it is necessary.
  copy:
    content: "{{ json | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: '0644'
  vars:
    json:
      graph: "{{ alternative_docker_dir }}"
      storage-driver: "{{ storage_driver }}"
  when: use_alternative_docker_root_dir
  notify: restart daemon and docker
  
- name: Ensure that daemon.json is empty.
  copy:
    content: "{ }"
    dest: /etc/docker/daemon.json
    mode: '0644'
  when: not use_alternative_docker_root_dir
  notify: restart daemon and docker
  
- name: Flush handlers
  meta: flush_handlers
  
