---
# handlers file for cciaas_doker_swarm

- name: install iptables
  yum:
    name: iptables.x86_64
    update_cache: true

- name: restart daemon and docker
  systemd:
    daemon_reload: true
    name: docker
    state: restarted
