---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
  - name: Check docker swarm status.
    shell: |
      set -o pipefail
      docker info | grep swarm -i
    register: swarm_status
    changed_when: false

  - name: Check if node is swarm manager.
    shell: |
      set -o pipefail
      docker info |grep 'is manager' -i
    register: is_swarm_manager
    changed_when: false

  - name: Assert that swarm is active on node and there are not errores.
    assert:
      that:
        - "'active' in swarm_status.stdout"
    when: "'docker_swarm_engine' in group_names"

  - name: Assert that master is swarm master and there are not errores.
    assert:
      that:
        - "'true' in is_swarm_manager.stdout"
    when: "'docker_swarm_manager' in group_names"

  - name: Assert that worker is swarm worker and there are not errores.
    assert:
      that:
        - "'false' in is_swarm_manager.stdout"
    when: "'docker_swarm_worker' in group_names"

  - name: Check that user docker exists.
    shell: |
      set -o pipefail
      cat /etc/passwd | grep docker | cut -d ':' -f 1
    register: output
    changed_when: false

  - name: Assert that docker user is created.
    assert:
      that:
        - "'docker' == output.stdout"
